### ISSUE TITLE
Clippy running on included crates.

### ISSUE THREAD

**Issue by Bas-Man** [zineland/zine#179]
Clippy appears to be testing all included crates and not just the code that Zine contains.

This might need to be changed to save on github time usage.

**Comment by Folyd** [comment]
Do you mean this CI task?

```yaml
    - name: Run clippy
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo clippy --release
```
