### ISSUE TITLE
Support adding co-authors for an article

### ISSUE THREAD

**Issue by Folyd** [zineland/zine#69]
To support co-authors, we simply need to change the `author` field to support both single plain string and string array.

```toml
[[article]]
# single author
author = "author1"
```

```toml
[[article]]
# multiple co-authors
author = ["author1", "author2"]
```

This needs custom deserialization for the `author` field. Similar to this: https://serde.rs/string-or-struct.html
