### ISSUE TITLE
Support cdn domain

### ISSUE THREAD

**Issue by Folyd** [zineland/zine#71]
If the user uploaded the `static` directory to CDN, then they can specify the 
CDN domain to speed up static assets request.

```toml
[site]
url = "xxx.tld"
cdn = "cdn.xxx.tld"
```

Zine will rewrite the CDN domain during the build stage.

Thanks @KernelErr 's suggestion.
